### ISSUE TITLE
使用 Icon 组件时,并不知道 name 支持那些值

### ISSUE THREAD

**Issue by cuilanxin** [uiwjs/react-native-uiw#244]

**Comment by jaywcjlove** [comment]
![image](https://user-images.githubusercontent.com/1680273/134886235-1bd96b6f-f51b-4360-9ffc-e2f98a58a067.png)

应该明显一些？还是 type 支持提示？
@cuilanxin

**Comment by jaywcjlove** [comment]
![image](https://user-images.githubusercontent.com/1680273/134936354-a023d24c-e59a-432e-be01-a7af974066cc.png)

@cuilanxin 没有破坏 Markdown 文档在 GitHub 中预览，又可以在 文档中预览。
