### ISSUE TITLE
参与组件开发，组件不能时时编译

### ISSUE THREAD

**Issue by cuilanxin** [uiwjs/react-native-uiw#246]
npm run lib:watch 
npm run lib:watch:examples

在 examples 
yarn run ios 

在 packages/core/src/Tooltip/index.tsx
export default class Tooltip extends React.Component<TooltipProps, TooltipState> {
  ... 
  render() { 
     // 新增一个打印
    console.log('object')
  }
}

在 packages/core/lib/Tooltip/index.tsx
export default class Tooltip extends React.Component<TooltipProps, TooltipState> {
  ... 
  render() { 
     // 新增一个打印
    console.log('object')
  }
}

在 examples/examples/lib/Tooltip/index.tsx
export default class Tooltip extends React.Component<TooltipProps, TooltipState> {
  ... 
  render() { 
    //这里本应该有新增一个打印 但是i并没有
  }
}

**Comment by jaywcjlove** [comment]
@cuilanxin 监听分开监听编译。

```bash
npm run lib:watch  # 编译组件
npm run lib:watch:base # 将组建编译到 base 示例中
npm run lib:watch:examples # 将组建编译到 examples 示例中
```

**Comment by cuilanxin** [comment]
我是这样做的，只有 npm run lib:watch 在我保存的时候会吧编译后的文件更新到 packages/core/lib ，
npm run lib:watch:base 和 npm run lib:watch:examples 在我保存的时候他们对应输出的文件并没有更新

**Comment by jaywcjlove** [comment]
@cuilanxin 这个是 bug 我在修复中。

**Comment by jaywcjlove** [comment]
@cuilanxin 已经修复

**Comment by cuilanxin** [comment]
好，我试试
