### ISSUE TITLE
依赖升级后导致 website 无法打开 

### ISSUE THREAD

**Issue by Amber-Nan** [uiwjs/react-native-uiw#365]
![23631641448658_ pic](https://user-images.githubusercontent.com/66067296/148339356-c15d3b30-c6a5-4595-8d9c-9bebe1357d41.jpg)
![image](https://user-images.githubusercontent.com/66067296/148339385-7471f1ee-672f-4685-9ea2-980df404c6f7.png)

**Comment by jaywcjlove** [comment]
@Amber-Nan 清理依赖重新安装。

**Comment by Amber-Nan** [comment]
> @Amber-Nan清理依赖重新安装。

新克隆的项目还是同样的报错

**Comment by Amber-Nan** [comment]
@jaywcjlove 新克隆的项目还是同样的报错

**Comment by Amber-Nan** [comment]
@jaywcjlove 新克隆的项目还是有同样的报错

**Comment by jaywcjlove** [comment]
这个是因为忘记`publicPath` 配置的问题。 看上去解决了
@Amber-Nan

**Comment by Amber-Nan** [comment]
@jaywcjlove 已测试，可以正常运行了
