### ISSUE TITLE
打包报错

### ISSUE THREAD

**Issue by jiaoxiaoyuan** [uiwjs/react-native-uiw#380]
![image](https://user-images.githubusercontent.com/25316619/182066052-c79d2df9-a4d7-4b08-88d4-08aa6f08cc4c.png)
请求解决

**Comment by jaywcjlove** [comment]
@jiaoxiaoyuan 使用的什么版本，在什么平台上打包错误的。

**Comment by jaywcjlove** [comment]
color 依赖包升级了？ `npm ls color` 看一下依赖。
@jiaoxiaoyuan

**Comment by jiaoxiaoyuan** [comment]
![image](https://user-images.githubusercontent.com/25316619/182066502-fe80598a-6940-46b3-9eb2-9ae164ac0ddc.png)
版本：
@uiw/react-native：^3.0.3
react-native：0.66.4

安卓打包

**Comment by jaywcjlove** [comment]
`npm ls color`

看一下 color 依赖版本

**Comment by jiaoxiaoyuan** [comment]
![image](https://user-images.githubusercontent.com/25316619/182066971-202bd456-68d4-4853-98ad-f4a54b422ac7.png)
└─┬ @uiw/react-native@3.0.3
  └── color@4.0.2

**Comment by jaywcjlove** [comment]
在当前项目安装 "color": "4.2.3" 依赖 锁死测试一下，不行安装 "color": "3.2.1" 测试一下。

**Comment by jaywcjlove** [comment]
安装 color 会覆盖依赖中的依赖 color 版本。我看报是因为 color 这个依赖包的问题，但是好几个依赖都依赖了它。

**Comment by jaywcjlove** [comment]
@jiaoxiaoyuan 先升级依赖  `@react-navigation/material-top-tabs` 6.2.1 升级到 6.2.2, 它更新了 color 依赖https://github.com/react-navigation/react-navigation/blob/741151654752e0e55affbc8e04dd4876eaedd760/packages/material-top-tabs/package.json#L44

**Comment by jaywcjlove** [comment]
@jiaoxiaoyuan 依赖 `@react-navigation/stack` 也要升级到 `6.2.2` 因为依赖 `"color": "^4.2.3",` 也升级了

https://github.com/react-navigation/react-navigation/blob/741151654752e0e55affbc8e04dd4876eaedd760/packages/stack/package.json#L44

**Comment by jiaoxiaoyuan** [comment]
![image](https://user-images.githubusercontent.com/25316619/182076170-4a229f88-af82-4fad-ba58-0b2b727e42de.png)

还是不行
@react-navigation/stack 也要升级到 6.2.2
@react-navigation/material-top-tabs 6.2.1 升级到 6.2.2

![image](https://user-images.githubusercontent.com/25316619/182076226-30c62238-afa9-4b21-b5c0-4bc45b45f0cd.png)

**Comment by jaywcjlove** [comment]
@jiaoxiaoyuan 我将 color 包升级一下，发一版，你测试一哈。

**Comment by jaywcjlove** [comment]
@jiaoxiaoyuan Upgrade `v3.0.4`

**Comment by jiaoxiaoyuan** [comment]
版本
react-native： 0.66.4
java -version =>openjdk version "1.8.0_275"
 @uiw/react-native: "3.0.3"
└─┬ @uiw/react-native@3.0.3
  └── color@4.0.2 

场景：
1、空项目，只引入了@uiw/react-native
2、页面只用了import {Icon} from '@uiw/react-native';

![image](https://user-images.githubusercontent.com/25316619/182104191-aff20a6e-3bf5-40c9-abb9-3746c63719c1.png)

![image](https://user-images.githubusercontent.com/25316619/182104248-4b062e75-9bd1-4937-a9c1-41c9ed5c498d.png)

![image](https://user-images.githubusercontent.com/25316619/182104317-67ceece6-9bd2-46a1-a1da-3695f1a76e4a.png)

**Comment by jaywcjlove** [comment]
@jiaoxiaoyuan ~~@uiw/react-native: "3.0.3"~~ 要升级到 `3.0.4`

**Comment by jaywcjlove** [comment]
这是因为依赖有 bug -> https://github.com/Qix-/color/blob/f746979c2090f7e4ccc3bd75e4efbe40eadf8975/index.js#L257

@jiaoxiaoyuan `3.0.4` 升级了 color 依赖包版本

https://github.com/uiwjs/react-native-uiw/blob/7259f52d6eba7b41f22834fb4237cc9cf0a8732b/packages/core/package.json#L59

**Comment by jiaoxiaoyuan** [comment]
🙏感谢，已解决
