### ISSUE TITLE
Calendar 日历组件Android样式问题

### ISSUE THREAD

**Issue by didiboji** [uiwjs/react-native-uiw#382]
Android模拟器，日历组件，按钮文字换行

![image](https://user-images.githubusercontent.com/52915367/184473025-c6f439d6-7b37-4aab-896b-77ed09e0b3df.png)

**Comment by matuancc** [comment]
<img width="365" alt="image" src="https://user-images.githubusercontent.com/33281802/184475979-cd53f957-ec6e-416e-a92d-6d30acd92849.png">
样式不太好看
