### ISSUE TITLE
List 列表期望支持如用户列表的需求

### ISSUE THREAD

**Issue by huqiaoli** [uiwjs/react-native-uiw#546]
<img width="337" alt="image" src="https://user-images.githubusercontent.com/13727848/221792018-5908bf27-5559-4b28-bbe9-43d80612a8ed.png">

**Comment by ChenlingasMx** [comment]
> <img alt="image" width="337" src="https://user-images.githubusercontent.com/13727848/221792018-5908bf27-5559-4b28-bbe9-43d80612a8ed.png">

可以使用renderItem 自定义列表样式
